services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - redis
      
  nginx:
    image: nginx
    container_name: nginx 
    ports:
    # Http Ports:
      - 80:80
      - 8080:8080
      - 8880:8880
      - 2052:2052
      - 2082:2082
      - 2086:2086
      - 2095:2095
    # Https Ports:
      - 443:443
      - 2053:2053
      - 2083:2083
      - 2087:2087
      - 2096:2096
      - 8443:8443
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

